docs: dco signing
Signed-off-by: jamesp918 <jamesp@botlet.io>

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,1 +1,13 @@
-node .husky/scripts/dco-sign.js "$1"
+# check 'Signed-off-by' in commit message
+git_commit_message=$(cat $1)
+if [[ "$git_commit_message" != *"Signed-off-by: "* ]]; then
+    echo
+    echo "\033[31mError\033[0m:"
+    echo "Commit message is missing the Signed-off-by line."
+    echo "Please use 'git commit -s' to commit your changes."
+    echo "You can add it manually with 'git commit --amend -s'."
+    echo
+    exit 1
+fi
+
+exit 0
